### PR TITLE
Update tests

### PR DESCRIPTION
**Pull request by whelena**

### CODE REVIEW

**Comment by whelena** [comment]
to retrieve files for testing suite, we switched to using `paste0(getcwd(), <files>)` instead of `system.file()`.
`system.file()` works when running `devtools::test()` but fails `devtools::check()` and `R CMD check`

**Comment by dan-knight** [comment]
> to retrieve files for testing (`test_vcf2bedpe` and `test_tabix`), we switched to using `paste0(getcwd(), <files>)` instead of `system.file()`. `system.file()` works when running `devtools::test()` but fails `devtools::check()` and `R CMD check`

Let's use `testthat::test_path('data/filename')` instead of `paste0(getwd(), '/filename')`. This seems to be a clearer and slightly more stable way of doing the same thing.

**Comment by whelena** [comment]
I think it's working for the windows tests now
Here's the result from `devtools::check_win_devel`
https://urldefense.com/v3/__https://win-builder.r-project.org/ofk910K961aH__;!!F9wkZZsI-LA!WrMZ3qPNCBiGkmIgnRC1pK08OeZ1mjZknqB694Ngk_IUMTjG9ohB-eCUtcusSojSvU2p$

Although now its failing the R-CMD-check on github

**Review by dan-knight — APPROVED** [review]
LGTM!

**Pull request merged**
